receivers:
  newrelicmssql:
    hostname: 74.225.24.140
    port: 1433
    username: "pkudikyala-wind\\pkudikyala"
    password: "Pkudikyala@1991"
    collection_interval: 300s  # 5 minutes for remote connections
    enable_ssl: true
    trust_server_certificate: true
    timeout: 300  # 5 minutes timeout for individual queries
    enable_buffer_metrics: true  # Disabled to reduce load
    enable_database_reserve_metrics: true
    enable_disk_metrics_in_bytes: true
    extra_connection_url_args: "connection timeout=300;command timeout=300;dial timeout=120;keepalive=30"

processors:
  batch:
    timeout: 30s
    send_batch_size: 512
    
  # Add resource attributes for New Relic
  resource:
    attributes:
      - key: service.name
        value: "azure-mssql-monitoring"
        action: upsert
      - key: service.version  
        value: "1.0.0"
        action: upsert
      - key: environment
        value: "staging"
        action: upsert
      - key: host.name
        value: "azure-sql-server"
        action: upsert

exporters:
  # New Relic Staging Exporter
  otlphttp/newrelic:
    endpoint: https://staging-otlp.nr-data.net
    headers:
      api-key: ""
    compression: gzip
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 100

  # Debug exporter for local troubleshooting
  debug:
    verbosity: normal

  # File exporter for backup
  file:
    path: /Users/pkudikyala/Documents/forked_repos/tanush_Otel/opentelemetry-collector-contrib/newrelic-metrics.json

service:
  pipelines:
    metrics:
      receivers: [newrelicmssql]
      processors: [resource, batch]
      exporters: [otlphttp/newrelic, debug, file]
  
  telemetry:
    logs:
      level: info
