receivers:
  newrelicmssql:
    hostname: 74.225.24.140
    port: 1433
    username: "pkudikyala-wind\\pkudikyala"
    password: "Pkudikyala@1991"
    collection_interval: 300s  # 5 minutes - much longer for remote connections
    enable_ssl: true
    trust_server_certificate: true
    timeout: 300  # 5 minutes timeout for individual queries
    enable_buffer_metrics: false  # Disabled to reduce query load
    enable_database_reserve_metrics: false  # Disabled to reduce query load
    enable_disk_metrics_in_bytes: false
    extra_connection_url_args: "connection timeout=300;command timeout=300;dial timeout=120;keepalive=30"  # Optimized for Azure

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  debug:
    verbosity: detailed

  otlp/newrelic:
    endpoint: https://staging-otlp.nr-data.net:4318
    headers:
      api-key: 5848a0c9c053a43ff9c2cc5af33cfe60FFFFNRAL
    compression: gzip

service:
  pipelines:
    metrics:
      receivers: [newrelicmssql]
      processors: [batch]
      exporters: [debug, otlp/newrelic]
  telemetry:
    logs:
      level: info  # Reduced log level
